# =============================================================================
# HYPRLAND CONFIG - Base funcional para personalización
# =============================================================================

# Sources files
source = ~/.config/hypr/generated/monitors.conf
source = ~/.config/hypr/generated/programs.conf
source = ~/.config/hypr/generated/autostart.conf
source = ~/.config/hypr/generated/env.conf
source = ~/.config/hypr/generated/decorations.conf
source = ~/.config/hypr/generated/animations.conf
source = ~/.config/hypr/generated/windowrules.conf
source = ~/.config/hypr/generated/layouts.conf
source = ~/.config/hypr/generated/misc.conf
source = ~/.config/hypr/generated/input.conf
source = ~/.config/hypr/generated/binds.conf

