$background = rgba(050505cc)
$foreground = rgba(c3c3c3ff)
$color0 = rgba(050505ff)
$color1 = rgba(6C6C6Cff)
$color2 = rgba(6E6E6Eff)
$color3 = rgba(727272ff)
$color4 = rgba(757575ff)
$color5 = rgba(797979ff)
$color6 = rgba(7C7C7Cff)
$color7 = rgba(c3c3c3ff)
$color8 = rgba(888888ff)
