-- autostart.lua
hl.on("hyprland.start", function()
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("bash -c 'sleep 1; awww img /home/v3nom/Downloads/Wallpapers/lanternKanji.jpg")
	hl.exec_cmd("bluetoothctl power on")
	hl.exec_cmd("bluetoothctl scan on")
	hl.exec_cmd("bash ~/.config/waybar/scripts/launch.sh")
	hl.exec_cmd("mako")
	-- Historial del clipboard (cliphist): guarda todo lo que copias, texto e imágenes
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
end)
