binde = ALT, return, exec, kitty
binde = SUPER, E, exec, nautilus
binde = SUPER SHIFT, D, exec, pkill rofi || rofi -show drun -theme ~/.config/rofi/style-3.rasi
binde = SUPER, W, exec, bash /home/v3nom/.config/hypr/scripts/wallrofi.sh
binde = ALT, F, exec, zen-browser
binde = ALT, W, killactive,
binde = ALT, P, layoutmsg, togglepseudotile
binde = ALT, SPACE, layoutmsg, togglesplit
binde = ALT, F11, fullscreen, 0
binde = ALT, R, exec, ~/.config/waybar/scripts/launch.sh
binde = ALT SHIFT, R, exec, ~/.config/hypr/scripts/reload.sh
binde = ALT, X, workspace, +1
binde = ALT, less, workspace, -1
binde = SUPER SHIFT, B, exec, ~/.config/rofi/scripts/bluetooth.sh
binde = SUPER SHIFT, W, exec, networkmanager_dmenu -dmenu 'rofi -dmenu -i -theme /home/v3nom/.config/rofi/style-3.rasi'
binde = ALT, l, movefocus, l
binde = ALT, h, movefocus, r
binde = ALT, k, movefocus, u
binde = ALT, j, movefocus, d
binde = ALT SHIFT, l, resizeactive, 30 0
binde = ALT SHIFT, h, resizeactive, -30 0
binde = ALT SHIFT, k, resizeactive, 0 -30
binde = ALT SHIFT, j, resizeactive, 0 30
binde = ALT, mouse_down, workspace, e+1
binde = ALT, mouse_up, workspace, e-1
binde = , Print, exec, grim ~/Pictures/screenshot_$(date +%F_%T).png
binde = SHIFT, Print, exec, grim -g "$(slurp)" ~/Pictures/screenshot_$(date +%F_%T).png
bindm = ALT, mouse:272, movewindow
bindm = ALT, mouse:273, resizewindow
bind = ALT, O, exec, hyprctl keyword decoration:active_opacity 1.0 && hyprctl keyword decoration:inactive_opacity 1.0
bind = ALT SHIFT, O, exec, hyprctl keyword decoration:active_opacity 1.00 && hyprctl keyword decoration:inactive_opacity 0.90
bind = SUPER, Escape, exec, wlogout --protocol layer-shell -b 3 --css ~/.config/wlogout/style.css --layout ~/.config/wlogout/layout
bind = SUPER, L, exec, hyprlock
bind = ALT, V, togglefloating
bind = CTRL, TAB, alterzorder, bottom
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
bind = , F9, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , F8, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , F7, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , F11, exec, brightnessctl set 5%+
bind = , F10, exec, brightnessctl set 5%-
bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = ALT, 1, exec, hyprsome workspace 1
bind = ALT SHIFT, 1, exec, hyprsome move 1
bind = ALT, 2, exec, hyprsome workspace 2
bind = ALT SHIFT, 2, exec, hyprsome move 2
bind = ALT, 3, exec, hyprsome workspace 3
bind = ALT SHIFT, 3, exec, hyprsome move 3
bind = ALT, 4, exec, hyprsome workspace 4
bind = ALT SHIFT, 4, exec, hyprsome move 4
bind = ALT, 5, exec, hyprsome workspace 5
bind = ALT SHIFT, 5, exec, hyprsome move 5
bind = ALT, 6, exec, hyprsome workspace 6
bind = ALT SHIFT, 6, exec, hyprsome move 6
bind = ALT, 7, exec, hyprsome workspace 7
bind = ALT SHIFT, 7, exec, hyprsome move 7
bind = ALT, 8, exec, hyprsome workspace 8
bind = ALT SHIFT, 8, exec, hyprsome move 8
bind = ALT, 9, exec, hyprsome workspace 9
bind = ALT SHIFT, 9, exec, hyprsome move 9
